Insert PwnedPasswordsTop100k from NCSC UK
OWASP/ASVS pull request #1061
Opened 2021-09-29 08:05 UTC by cmlh

Signed-off-by: Christian Heinrich <christian.heinrich@cmlh.id.au>

This Pull Request relates to issue #1055

NCSC has been specified as UK due to multiple NCSC within EU.

Supported by @jmanico within https://github.com/OWASP/ASVS/issues/1055#issuecomment-927393889

2021-09-29 09:15 UTC, elarlang commented
We do not put links into requirement texts

2021-09-30 18:29 UTC, jmanico commented
Christian, can you kindly move the link to bottom on this section and make the requirement a bit more neutral?

2021-09-30 18:32 UTC, jmanico commented
| **2.1.14** | [ADDED, SPLIT FROM 2.1.7, LEVEL L1 > L3] Verify that passwords submitted during account registration or password changes are verified against a list of of breached passwords. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | | ✓ | | 5.1.1.2 |

2021-09-30 23:06 UTC, jmanico requested changes
should include [PwnedPasswordsTop100k from NCSC UK] is difinitive language we need to avoid. Can you rephrase this as citing this resource as one of many potential lists, API's and resources? Thank you!

2021-09-30 23:06 UTC, jmanico commented on 4.0/en/0x11-V2-Authentication.md
> +"_...list of of breached passwords._" should include [PwnedPasswordsTop100k from NCSC UK](https://www.ncsc.gov.uk/blog-post/passwords-passwords-everywhere#:~:text=PwnedPasswordsTop100k.txt).
Please change "should include" to something more along the lines of citing this as one of many resources.

2021-09-30 23:12 UTC, jmanico commented
Christian, I think this is a really good resource, but can you work on word-smithing this addition here...
https://github.com/OWASP/ASVS/issues/1055 
....and once you and at least one other leader are in alignment, then let's go to PR! Please.

2022-02-23 18:30 UTC, closed without merging