Remove 6.2.3 as a duplicate
OWASP/ASVS pull request #1457
Opened 2022-12-20 07:08 UTC by tghosth

This Pull Request relates to issue #1198

2022-12-20 07:10 UTC, tghosth commented
@jmanico any further comments or questions? See my notes here: https://github.com/OWASP/ASVS/issues/1198#issuecomment-1358924019

2022-12-20 07:10 UTC, tghosth commented
@set-reminder 2 weeks merge if no adverse feedbac

2022-12-20 09:52 UTC, elarlang requested changes

2022-12-20 09:52 UTC, elarlang commented on 5.0/en/0x14-V6-Cryptography.md
> +| **6.2.3** | [DELETED] | | | | |
`[DELETED, DUPLICATE OF 6.2.5]`

2022-12-20 12:45 UTC, tghosth commented on 5.0/en/0x14-V6-Cryptography.md
> +| **6.2.3** | [DELETED] | | | | |
Fixed

2022-12-20 14:01 UTC, elarlang approved these changes

2023-01-02 23:04 UTC, jmanico approved these changes

2023-01-02 23:04 UTC, merged