Clarifying file download requirements
OWASP/ASVS pull request #1458
Opened 2022-12-20 08:04 UTC by tghosth

This Pull Request relates to issue #1206

2022-12-20 08:04 UTC, tghosth commented
@jmanico what do you think of this modification?

@set-reminder 3 weeks merge if no adverse feedback

2022-12-20 10:05 UTC, elarlang requested changes
Discussion in issue
https://github.com/OWASP/ASVS/issues/1206#issuecomment-1359112398

2022-12-20 10:53 UTC, tghosth commented
See my response (https://github.com/OWASP/ASVS/issues/1206#issuecomment-1359174384) and updated PR

2022-12-20 11:06 UTC, elarlang approved these changes

2023-01-02 23:03 UTC, jmanico approved these changes

2023-01-02 23:03 UTC, merged