Clarify 12.1.1 as per #1384
OWASP/ASVS pull request #1514
Opened 2023-01-05 18:39 UTC by tghosth

This Pull Request relates to issue #1384

2023-01-05 18:47 UTC, elarlang requested changes

2023-01-05 18:47 UTC, elarlang commented on 5.0/en/0x20-V12-Files-Resources.md
> +| **12.1.1** | Verify that the application will not accept large files that could cause a denial of service when they are processed. | ✓ | ✓ | ✓ | 400 |
khm. MODIFIED

2023-01-05 18:56 UTC, elarlang commented
https://github.com/OWASP/ASVS/issues/1384#issuecomment-1372609416

2023-01-08 15:28 UTC, tghosth commented on 5.0/en/0x20-V12-Files-Resources.md
> +| **12.1.1** | Verify that the application will not accept large files that could cause a denial of service when they are processed. | ✓ | ✓ | ✓ | 400 |
Fixed

2023-01-09 11:03 UTC, tghosth commented
Ok I modified as per https://github.com/OWASP/ASVS/issues/1384#issuecomment-1374934243

2023-01-09 12:02 UTC, elarlang approved these changes

2023-01-09 12:03 UTC, merged