Added POC for CycloneDX v1.6 (snapshot) standard support
OWASP/ASVS pull request #1676
Opened 2023-07-03 20:12 UTC by stevespringett

Added POC for CycloneDX v1.6 (snapshot) standard support. Feel free to use this as is, or create a derivative. It has been tested and proven to work. This script is responsible for generating https://github.com/CycloneDX/official-3rd-party-standards/blob/main/standards/OWASP_ASVS/asvs-4.0.3.cdx.json

Closes #1675

2023-07-06 11:46 UTC, tghosth requested changes

2023-07-06 21:43 UTC, stevespringett commented on 4.0/tools/export.py
> +parser.add_argument('--format', choices=['json', 'json_flat', 'xml', 'csv', 'cdx_json', 'cdx_xml'], default='json')
Good catch. No, it does not. I just removed it.

2023-07-09 11:45 UTC, tghosth commented
Thanks @stevespringett, did you see my PR https://github.com/stevespringett/ASVS/pull/1 ?

2023-09-06 14:21 UTC, tghosth commented
Hi @stevespringett, did you see [my PR](https://github.com/stevespringett/ASVS/pull/1) on your original PR? Can you merge it in and then I get get this merged?

2023-09-07 04:01 UTC, stevespringett commented
@tghosth Thanks for the ping. Merged in your PR so hopefully this will be ready to go.

2023-09-07 09:48 UTC, tghosth approved these changes

2023-09-07 09:48 UTC, merged