Fix-13.2.x
OWASP/ASVS pull request #1685
Opened 2023-07-10 15:21 UTC by tghosth

This Pull Request relates to issues #1525 and #1207

2023-07-12 08:39 UTC, elarlang requested changes
For 13.1.6 please use the label: `MODIFIED, MOVED FROM 13.2.6, LEVEL L2 > L3`

2023-07-12 09:55 UTC, tghosth commented
ok is that better @elarlang ?

2023-07-12 12:10 UTC, elarlang commented
> ok is that better @elarlang ?

yes, but keep `[ .. ]`

2023-07-12 18:49 UTC, tghosth commented
Ugh sorry should be better now 🤦‍♂️🤦‍♂️🤦‍♂️

2023-07-13 08:12 UTC, elarlang approved these changes

2023-07-13 08:12 UTC, merged