Clarify wording of 2.2.4 to resolve #1340
OWASP/ASVS pull request #1689
Opened 2023-07-12 10:38 UTC by tghosth

This Pull Request relates to issue #1340

2023-07-12 12:08 UTC, elarlang requested changes
we don't use markdown syntax in requirement text for styling (`**`)

2023-07-12 18:46 UTC, tghosth commented
Yep you are 100% correct, thanks! How about now?

2023-07-12 18:54 UTC, jmanico approved these changes

2023-07-13 08:11 UTC, elarlang approved these changes

2023-07-13 08:11 UTC, merged