Update 0x18-V10-Malicious.md
OWASP/ASVS pull request #1792
Opened 2023-11-22 19:46 UTC by ImanSharaf

Removed 10.3.3 based on https://github.com/OWASP/ASVS/issues/1788

This Pull Request relates to issue #...

2023-11-22 19:50 UTC, elarlang commented
I removed 2 related links also. As @jmanico did not comment for final decision, I set him as reviewer.

2023-11-23 12:34 UTC, tghosth approved these changes

2023-11-27 18:42 UTC, elarlang commented
ping @jmanico

2023-11-27 20:32 UTC, jmanico requested changes
Here is a minor modification to make it more readable...

Verify that the application is protected against subdomain takeovers if the application depends on DNS entries or DNS subdomains. This includes being vigilant about expired domain names, outdated DNS pointers or CNAMEs, expired projects in public source code repositories, or transient cloud APIs, serverless functions, and storage buckets (e.g., *autogen-bucket-id*.cloud.example.com). Implement protections by regularly auditing DNS names utilized by the application to detect and address any expirations or modifications.

2023-11-27 20:34 UTC, jmanico approved these changes

2023-11-27 20:34 UTC, merged