Clarify token terminology throughout to resolve #2414
OWASP/ASVS pull request #2434
Opened 2024-12-05 13:32 UTC by tghosth

This Pull Request relates to issue #2414

@ryarmst @elarlang @randomstuff @TobiasAhnoff

2024-12-05 15:05 UTC, elarlang requested changes
I feel we are looping with this one and PR is different than agreed in the related issue.

* I prefer V52 title to be "Self-contained tokens" as it was.
* V4.2.5 should use self-contained tokens
* "Self-Contained Token - A subset of cryptographically secured tokens" - I really don't like that. It's not a subset, self-contained tokens are using cryptography for integrity. Whatever uses crypto for integrity is not subset of it, those are just using it. I think those proposals were good: https://github.com/OWASP/ASVS/issues/2414#issuecomment-2506815656

2024-12-05 16:00 UTC, tghosth commented
Commented in the issue

2024-12-06 18:51 UTC, elarlang commented on 5.0/en/0x12-V3-Session-management.md
> +For stateful session mechanisms, this should just require invalidating the session at the backend. If self-contained tokens are being used, a way to revoke these tokens will be needed.
revoke or block

2024-12-06 19:17 UTC, elarlang approved these changes
Let's get those in. If needed, we can do another update.

2024-12-06 19:17 UTC, merged